### Reading Data From Different Sources

In [1]:
import pandas as pd
from io import StringIO

Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title":"Team Lead", "title2":"Sr. Developer"}]}'

df = pd.read_json(StringIO(Data))  # Read JSON string and convert it into a DataFrame
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title': 'Team Lead', 'title2': 'Sr. Developer'}"

In [2]:
df.to_json() # convert dataframe to json

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title":"Team Lead","title2":"Sr. Developer"}}}'

In [3]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title":"Team Lead","title2":"Sr. Developer"}}}'

In [4]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title":"Team Lead","title2":"Sr. Developer"}}]'

In [ ]:
# read data from a url
df = pd.read_csv('https://gist.githubusercontent.com/tijptjik/9408623/raw/b237fa5848349a14a14e5d4107dc7897c21951f5/wine.csv')
df

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [6]:
# convert this data from url to csv
df.to_csv('wine.csv')

In [10]:
# read data from HTML file
url = "https://www.fdic.gov/bank/individual/failed/banklist.html"

df = pd.read_html(url)
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [21]:
df_excel = pd.read_excel('sample-chocolate-sales-data-all.xlsx')
df_excel

     ShipmentID  SPID  PID GID   Shipdate    Amount  Boxes Order_Status
0     S00000012  SP01  P01  G5 2023-12-12   5609.25    374    Delivered
1     S00000042  SP01  P01  G4 2023-10-26   7197.75    450    Delivered
2     S00000058  SP01  P01  G3 2024-06-28  13279.50   1107    Delivered
3     S00000088  SP01  P02  G1 2023-04-03   1919.25    138    Delivered
4     S00000095  SP01  P02  G5 2023-12-25   2324.25    146    Delivered
...         ...   ...  ...  ..        ...       ...    ...          ...
7900  S00191176  SP21  P22  G5 2023-09-08   8538.75    427    Delivered
7901  S00191181  SP21  P22  G6 2023-02-01  11569.50    579    Delivered
7902  S00191195  SP21  P22  G6 2024-06-17   6014.25    335    Delivered
7903  S00191196  SP21  P22  G6 2023-06-14   8696.25    484    Delivered
7904  S00191241  SP21  P22  G4 2024-06-03   9654.75    537    Delivered

[7905 rows x 8 columns]

### What is Pickle

Pickle is a Python-specific file format designed for serializing and deserializing objects, where serialization (also called pickling) transforms Python object hierarchies into a byte stream, and deserialization (or unpickling) reverses this process, converting a byte stream back into Python objects. While the pickle format is unique to the Python ecosystem, the concepts of serialization and deserialization are common across various programming languages. Through pickling, Python objects can be converted into a format that can be stored or transmitted, and subsequently, unpickling restores these objects from the stored format back to their original state.

In [22]:
df_excel.to_pickle('df_excel')

In [23]:
pd.read_pickle('df_excel')

     ShipmentID  SPID  PID GID   Shipdate    Amount  Boxes Order_Status
0     S00000012  SP01  P01  G5 2023-12-12   5609.25    374    Delivered
1     S00000042  SP01  P01  G4 2023-10-26   7197.75    450    Delivered
2     S00000058  SP01  P01  G3 2024-06-28  13279.50   1107    Delivered
3     S00000088  SP01  P02  G1 2023-04-03   1919.25    138    Delivered
4     S00000095  SP01  P02  G5 2023-12-25   2324.25    146    Delivered
...         ...   ...  ...  ..        ...       ...    ...          ...
7900  S00191176  SP21  P22  G5 2023-09-08   8538.75    427    Delivered
7901  S00191181  SP21  P22  G6 2023-02-01  11569.50    579    Delivered
7902  S00191195  SP21  P22  G6 2024-06-17   6014.25    335    Delivered
7903  S00191196  SP21  P22  G6 2023-06-14   8696.25    484    Delivered
7904  S00191241  SP21  P22  G4 2024-06-03   9654.75    537    Delivered

[7905 rows x 8 columns]